name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run composer
        uses: ErickGomez98/composer@master
        with:
          action: 'install'

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v2
        env:
          TEST_NAME: GitHubActions
        with:
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          args: --coverage-text