name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: imagick, gd-php/php-src@PHP-8.0, zlib, zxing
        env:
          GD_CONFIGURE_OPTS: --enable-gd=shared,/usr --with-external-gd --with-jpeg
          GD_LIBS: libgd-dev libjpeg-dev
          GD_PATH: ext/gd


      - uses: php-actions/composer@v5

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v2
        env:
          TEST_NAME: GitHubActions
        with:
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          args: --coverage-text
